### PR TITLE
Update for calibration with the new Robotino shell

### PR DESCRIPTION
**Pull request by ipa-rmb**
- should run with the newest robotino setup
- also adds code for camera-arm calibration that ran successfully on rob@work at IPA (further adaptation to Squirrel Robotino will follow soon)

@mzillich @edith-langer could you please test with this branch whether calibration of the pan tilt camera still works properly? It should all still follow the guidelines in the ROS Wiki, so there are hopefully only changes in code structure and topics of robotino introduced by this update. At least it cleanly compiled on my computer, but I could not test it yet.

### CODE REVIEW

**Comment by NadiaHG** [comment]
Sorry I renamed the topics of the shell to:

/neck_pan_controller/joint_group_position_controller/command --> /shell_controller/neck_pan_controller/command [std_msgs/Float64]

/neck_tilt_controller/joint_group_position_controller/command -->  /shell_controller/neck_tilt_controller/command [std_msgs/Float64]

see: https://github.com/ipa-rmb/squirrel_calibration/pull/2 please merge if it is right
You can test this PR on simulation with the following versions:

https://github.com/squirrel-project/squirrel_robotino/pull/209
https://github.com/squirrel-project/squirrel_common/pull/231

**Comment by ipa-rmb** [comment]
Thanks, I merged your PR. @mzillich @edith-langer feel free to test it with the robot. I will test it in simulation as well.

**Comment by ipa-rmb** [comment]
Calibration passed the simulation test successfully together with

https://github.com/squirrel-project/squirrel_robotino/pull/210 

https://github.com/squirrel-project/squirrel_common/pull/232

**Comment by NadiaHG** [comment]
@ipa-rmb buildbot fails:

`/tmp/squirrel_calibration_indigo_prtestbuild/src/squirrel_calibration/relative_localization/common/src/relative_localization_utilities.cpp: In function 'bool RelativeLocalizationUtilities::fitLine(const std::vector<cv::Point_<double> >&, cv::Vec4d&, double, double, double, bool)':
/tmp/squirrel_calibration_indigo_prtestbuild/src/squirrel_calibration/relative_localization/common/src/relative_localization_utilities.cpp:130:3: error: 'fitLine' is not a member of 'cv'
   cv::fitLine(inlier_set, line_ls, CV_DIST_L2, 0, 0.01, 0.01); // (vx, vy, x0, y0), where (vx, vy) is a normalized vector collinear to the line and (x0, y0) is a point on the line
   ^`

could you please take a look?

**Review by NadiaHG — APPROVED** [review]

**Pull request merged**
